version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: data for greenweez ecommerce
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: details about sales
      - name: product
        identifier: raw_gz_product
        description: details about product
        columns: 
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null 
      - name: ship
        identifier: raw_gz_ship
        description: details about ship
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
              
